### ISSUE TITLE
Auto update does not work if properties in Lens are changed

### ISSUE THREAD

**Issue by chbergmann** [chbergmann/OpticsWorkbench#12]
When I change the Refraction index property. The first change automatically updates the refraction path of the ray. Sometimes, further changes in the index update the ray, sometimes not. (I have yet to tie down a repeatable sequence to replicate, sorry.)

**Comment by wohltat** [comment]
I've experienced the same or at least similar thing.
'Mark to recompute' the ray, then the recompute works two times but not after that.

As i see it, there is no auto update at the moment.

**Comment by luzpaz** [comment]
@MSLDgit did the fix in #36 solve this issue ?

**Comment by chbergmann** [comment]
Changes in the Lens properties do not have any influence on the present rays automatically any more. You have to trigger (Re)start Simulation manually to get the rays updated. I do not see a way to change this behavior. Therefore I close this issue.
