### ISSUE TITLE
Refracted rays are calculated incorrectly

### ISSUE THREAD

**Issue by JRaacke** [chbergmann/OpticsWorkbench#19]
At a lens surface, the refracted ray does not follow snell's law. When constructed manually using snell's law constraint, the ray has a different direction.
Please verify, if it's only a missing ^2 in ray.py:

def snellsLaw(self, ray, n1, n2, normal):
        #print('snell ' + str(n1) + '/' + str(n2))
        root = 1 - **(n1/n2)*(n1/n2)** * normal.cross(ray) * normal.cross(ray)
        if root < 0: # total reflection
            return self.mirror(ray, normal)

        return -n1/n2 * normal.cross( (-normal).cross(ray)) - normal * math.sqrt(root)

**Comment by chbergmann** [comment]
You are right. I fixed it. Thanks for reporting.
