### ISSUE TITLE
Point source on lens edge crashes Freecad

### ISSUE THREAD

**Issue by JRaacke** [chbergmann/OpticsWorkbench#21]
If a lens was drawn through the origin of the sketch, Freecad crashes when a 2D beam bundle is placed. 
Since the bundle is placed into the origin, the lengths of ray vectors hitting the surface are zero and therefore their direction cannot be calculated. Probably it is a "division by zero", which should be catched.

**Comment by chbergmann** [comment]
fixed in in version 1.1
