### ISSUE TITLE
Refraction at touching elements

### ISSUE THREAD

**Issue by JRaacke** [chbergmann/OpticsWorkbench#22]
If lenses are sharing a face, a beam coming from the outside is not refracted at the internal inferface.
If a beam is is coming from the inside of one element (e.g. fluorescence), it is refracted at the internal inferface, but not at the outer surface of the other element.

![Refraction-Demo](https://user-images.githubusercontent.com/93308861/151757539-ce69213d-5f85-40dd-8290-5a52bc20bddf.png)

**Comment by chbergmann** [comment]
this should work now (V 1.0.4)
