### ISSUE TITLE
Ray from inside a medium are refracted with reciprocal index

### ISSUE THREAD

**Issue by JRaacke** [chbergmann/OpticsWorkbench#23]
Rays starting inside a medium behave like they are starting outside of the medium. All refractions seem to be using 1/n for calculation.

The two rays in the screenshot are constructed to have the same angles inside the left medium (diamond, n=2.41). The right medium block is simple window glass. The ray coming from outside is OK.

![Bug](https://user-images.githubusercontent.com/93308861/151931036-093a30c5-889d-4831-9a4d-967184e9626f.png)

**Comment by chbergmann** [comment]
I do not see a method to find out if a point is inside or outside a closed wire.

**Comment by JRaacke** [comment]
The straight ray to infinity will cross the closed wire an odd number of times, if the starting point is inside.

**Comment by chbergmann** [comment]
Thanks for the hint. This was the solution to fix this issue.

**Comment by chbergmann** [comment]
still not working in any cases

**Comment by chbergmann** [comment]
now it works
