### ISSUE TITLE
ray disappears when using transform

### ISSUE THREAD

**Issue by wohltat** [chbergmann/OpticsWorkbench#3]
When the ray is transformed, even without changing anything, it disappears. If i hide and unhide the ray it appears again

![opticsWB_transform_bug](https://user-images.githubusercontent.com/4751351/129790563-733ca5c1-9a00-42fb-91e0-9bf2529e3a4b.gif)

Alt + O is like pressing OK

**Comment by chbergmann** [comment]
I cannot reproduce this issue. Anyway, this is a FreeCAD issue which I propably cannot solve.

**Comment by wohltat** [comment]
I use realthunder Link branch. Maybe this is why you cannot reproduce.

```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

```

**Comment by chbergmann** [comment]
Closing because this issue is related to realthunders branch
