### ISSUE TITLE
Which part of the code is about visualizing the rays?

### ISSUE THREAD

**Issue by LiXinrong1012** [chbergmann/OpticsWorkbench#40]
Hi, nice work on optical design. I just wonder which part of the code is corresponding to visualizing the rays? It may be helpful for my project.

**Comment by chbergmann** [comment]
redrawRay() in Ray.py creates an array of lines. To visualize then they have to be added to Shape of a Part::FeaturePython object.
fp.Shape = Part.makeCompound(linearray)
