### ISSUE TITLE
How to create array of optical emitter with a spherical shape (beam angle adjustable)?

### ISSUE THREAD

**Issue by fish1968** [chbergmann/OpticsWorkbench#50]
I turned on the spherical option, and input 25 degree, but the light from the surface is still always vertical to the surface.

Or, is it possible to create one spherical beam, then duplicate it into an array? I tried part design -> Linear pattern, but it only supports "addictive or subtractive features were allowed. 

![image](https://github.com/user-attachments/assets/5df49432-3735-4fae-9f9f-a27092eb8991)

**Comment by fish1968** [comment]
I use A Python Script like this: 

```Python
import FreeCAD, FreeCADGui
from FreeCAD import Base

# Get the active document
doc = FreeCAD.ActiveDocument

# Parameters for the array
num_duplicates_x = 10  # Number of beams in the X direction
num_duplicates_y = 10  # Number of beams in the Y direction
num_duplicates_z = 1  # Number of beams in the Z direction
spacing = Base.Vector(1, 2, 1)  # Spacing vector

# Get the original beam at its placement
original_beam = doc.getObject("Beam")

# Check if the original beam exists
if original_beam is None:
    print("Object 'Beam' not found.")
else:
    # Get the original position and rotation
    original_position = original_beam.Placement.Base
    original_rotation = original_beam.Placement.Rotation

    # Move each beam from Beam001 to Beam100
    for x in range(num_duplicates_x):
        for z in range(num_duplicates_z):
            # Create the name of the object to move
            beam_name = f"Beam{str(x * num_duplicates_z + z + 1).zfill(3)}"  # "Beam001", "Beam002", ..., "Beam100"

            # Get the object
            beam_obj = doc.getObject(beam_name)

            if beam_obj:
                # Calculate the new position based on the original position
                new_position = original_position + Base.Vector(
                    spacing.x * x,   # X position
                    spacing.y * 0,   # Y position (0 since we only want a 1-row array)
                    spacing.z * z    # Z position
                )

                # Set the new placement
                beam_obj.Placement = Base.Placement(new_position, original_rotation)
                print(f"Moved {beam_name} to {new_position}")

    # Recompute the document to update the changes
    doc.recompute()
    print("All specified beams moved to their new positions.")
```

**Comment by fish1968** [comment]
> I use A Python Script like this:
> 
> ```python
> import FreeCAD, FreeCADGui
> from FreeCAD import Base
> 
> # Get the active document
> doc = FreeCAD.ActiveDocument
> 
> # Parameters for the array
> num_duplicates_x = 10  # Number of beams in the X direction
> num_duplicates_y = 10  # Number of beams in the Y direction
> num_duplicates_z = 1  # Number of beams in the Z direction
> spacing = Base.Vector(1, 2, 1)  # Spacing vector
> 
> # Get the original beam at its placement
> original_beam = doc.getObject("Beam")
> 
> # Check if the original beam exists
> if original_beam is None:
>     print("Object 'Beam' not found.")
> else:
>     # Get the original position and rotation
>     original_position = original_beam.Placement.Base
>     original_rotation = original_beam.Placement.Rotation
> 
>     # Move each beam from Beam001 to Beam100
>     for x in range(num_duplicates_x):
>         for z in range(num_duplicates_z):
>             # Create the name of the object to move
>             beam_name = f"Beam{str(x * num_duplicates_z + z + 1).zfill(3)}"  # "Beam001", "Beam002", ..., "Beam100"
> 
>             # Get the object
>             beam_obj = doc.getObject(beam_name)
> 
>             if beam_obj:
>                 # Calculate the new position based on the original position
>                 new_position = original_position + Base.Vector(
>                     spacing.x * x,   # X position
>                     spacing.y * 0,   # Y position (0 since we only want a 1-row array)
>                     spacing.z * z    # Z position
>                 )
> 
>                 # Set the new placement
>                 beam_obj.Placement = Base.Placement(new_position, original_rotation)
>                 print(f"Moved {beam_name} to {new_position}")
> 
>     # Recompute the document to update the changes
>     doc.recompute()
>     print("All specified beams moved to their new positions.")
> ```

But any adjustment on the first Beam is not directly mapped to other beams, not very convenient, when things need modification frequently.

**Comment by chbergmann** [comment]
You can do this in a much easier way:

import OpticsWorkbench
for i in range(0, 10):
	beam=OpticsWorkbench.makeRay(beamNrColumns=8, beamNrRows=8, spherical=True, coneAngle=25)
	beam.Placement.Base.x = i*10

**Comment by fish1968** [comment]
> import OpticsWorkbench
> for x in range(0, 10):
>     for y in range(0, 10):
>         beam=OpticsWorkbench.makeRay(beamNrColumns=4, beamNrRows=4, spherical=True, coneAngle=25)
>         beam.Placement.Base = FreeCAD.Vector(x*10, y*10, 0)

Really Cool, Thank you!

As for the "Optical Emitter" button, It seems that cone angle obtained is not determined by parameter, but by the angle of the surface / object attached and is always normal to the local surface.

![image](https://github.com/user-attachments/assets/337adda6-c1f1-47b4-b427-bf5220d004d3)

I can build a matched surface to create desired cone angle.

Comparatively, using your script is much easier. 

Many thanks!
