### ISSUE TITLE
[Feature] Adding translations to Optics workbench and using crowdin to manage them

### ISSUE THREAD

**Issue by luzpaz** [chbergmann/OpticsWorkbench#52]
@chbergmann We're trying to get popular workbenches translated and into [crowdin](https://crowdin.com/project/freecad-addons)

* https://github.com/FreeCAD/FreeCAD-addons/issues/187

Any interest in that ?

/cc @kaktusus & @hasecilu

**Comment by chbergmann** [comment]
I can do that when I have time.

**Comment by hasecilu** [comment]
Check my PRs on Render and CfdOF WBs, there is implemented the translation support in the correct way.

**Comment by luzpaz** [comment]
What's the status here ?

**Comment by chbergmann** [comment]
translations for German and Chinese have been added

**Comment by luzpaz** [comment]
I only see the german translations in https://github.com/chbergmann/OpticsWorkbench/blob/main/translations/ 

Also, is there a reason you're keeping the .qm file ?

Are you planning to use Crowdin, like other workbenches are ?

**Comment by hasecilu** [comment]
Also it's good idea to include the agnostic file (a clean file with no locale and no translations) for people that wants to also translate it.

**Comment by chbergmann** [comment]
> I only see the german translations in https://github.com/chbergmann/OpticsWorkbench/blob/main/translations/
Chinese files have been added

> Also, is there a reason you're keeping the .qm file ?
Yes, they are needed to display the selected language. qm files are not generated automatically if somebody installs the Optics workbench.
 
> Are you planning to use Crowdin, like other workbenches are ?
I asked Yorik again for access to the FreeCAD-addons project. Once I got it I will do.

**Comment by chbergmann** [comment]
The agnostic file got lost, but anybody can use 

> Also it's good idea to include the agnostic file (a clean file with no locale and no translations) for people that wants to also translate it.
I do not have one. But it is also easy to use any file in another language and exchange the translations. Or use crowdin once I got access and uploded the translations.

**Comment by hasecilu** [comment]
This WB has been added to CrowdIn, translations synced.
