### ISSUE TITLE
Strange behavior of rays

### ISSUE THREAD

**Issue by SkifDen** [chbergmann/OpticsWorkbench#53]
Bug or feature.
Checked on different machines and OS.
When the beam hits the contour of the object, the beam is refracted.
To get rid of the effect, I rotate the source by 1 degree and shift it by 0.1 micrometer.
![image](https://github.com/user-attachments/assets/cc467064-0844-4d96-9fa8-3696377fa3d4)

![image](https://github.com/user-attachments/assets/5471362d-5147-42c5-bb4b-349f32982a48)

![image](https://github.com/user-attachments/assets/570bd9eb-0a29-4559-84f3-cb2206ccd9f9)

![image](https://github.com/user-attachments/assets/55de330d-c4dd-4730-97ec-192a152652cd)

![image](https://github.com/user-attachments/assets/c7793ba3-8d48-4964-80d1-53e868af6bb2)
[test.zip](https://github.com/user-attachments/files/17591488/test.zip)

**Comment by chbergmann** [comment]
if the light source is lying on the border of a lens, the tool has problems to detect if the ray is inside or outside the lens. The direction of refraction may be wrong in this case. Moving the ray by 0.1 micrometer makes it be clearly inside or outside

**Comment by SkifDen** [comment]
I moved the source inward by 1 mm - the problem remained.
![image](https://github.com/user-attachments/assets/4dce36a6-89c9-465d-9631-7b4f0dd6125e)

**Comment by SkifDen** [comment]
![image](https://github.com/user-attachments/assets/6533dda5-2c97-40e3-8668-a2d1edaafbe1)

**Comment by SkifDen** [comment]
"_Moving the ray by 0.1 micrometer makes it be clearly inside or outside_"
I shifted it by 0.1 mm perpendicular to the main optical axis of the lens, i.e. I set 0.1 mm between the optical axis of the lens and the source

**Comment by chbergmann** [comment]
It looks like your pipe is not water tight. There are holes along the weld caused by rounding errors of the internally used float values. Shifting the beam a small fraction to the side would minimize the chance to hit the weld.
A better solution would be creating a bended pipe from a loft over an array of circles

**Comment by SkifDen** [comment]
This is not a pipe, this is an imitation of fiber optics. The model was made using FreeCAD - Part Sweep (https://wiki.freecad.org/Part_Sweep). I also tried using step -format from other CADs, the same effect.
![image](https://github.com/user-attachments/assets/44503ad5-fbbe-480e-bc7b-abdd0aa3a8cb)

**Comment by chbergmann** [comment]
no matter if you call it pipe or something else, the problem is that simulated rays may not be reflected at the edges of some surfaces, because the algorithms do not detect an intersection with any surface or edge line. I do not see a possibility to fix this.

**Comment by SkifDen** [comment]
Maybe this is somehow related to the representation of the lens in 2D? Rays in 2D somehow define the contour.
![image](https://github.com/user-attachments/assets/154c3de9-67ef-4b2a-9498-6aefde223714)

**Comment by chbergmann** [comment]
good news: I was able to fix your error. Please update the workbench. I found a better algorithm to detect if a ray is inside or outside a 3D lens

**Comment by SkifDen** [comment]
Thank you very much, everything works correctly.

**Comment by SkifDen** [comment]
The new version "Ray.py" has commented out the output of the number of rays created
#print("Number of rays created = ",Ncount)
